$primary_paletteKeyColor = 27838a
$secondary_paletteKeyColor = 627c7e
$tertiary_paletteKeyColor = 687797
$neutral_paletteKeyColor = 727879
$neutral_variant_paletteKeyColor = 6f797a
$background = 0e1415
$onBackground = dde4e4
$surface = 0e1415
$surfaceDim = 0e1415
$surfaceBright = 343a3b
$surfaceContainerLowest = 090f10
$surfaceContainerLow = 161d1d
$surfaceContainer = 1a2121
$surfaceContainerHigh = 252b2c
$surfaceContainerHighest = 303636
$onSurface = dde4e4
$surfaceVariant = 3f4849
$onSurfaceVariant = bec8c9
$inverseSurface = dde4e4
$inverseOnSurface = 2b3232
$outline = 899393
$outlineVariant = 3f4849
$shadow = 000000
$scrim = 000000
$surfaceTint = 80d4db
$primary = 80d4db
$onPrimary = 00363a
$primaryContainer = 004f54
$onPrimaryContainer = 9df0f8
$inversePrimary = 00696f
$secondary = b1cbce
$onSecondary = 1b3436
$secondaryContainer = 324b4d
$onSecondaryContainer = cce8ea
$tertiary = b7c7ea
$onTertiary = 21304c
$tertiaryContainer = 8191b2
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = 9df0f8
$primaryFixedDim = 80d4db
$onPrimaryFixed = 002022
$onPrimaryFixedVariant = 004f54
$secondaryFixed = cce8ea
$secondaryFixedDim = b1cbce
$onSecondaryFixed = 051f21
$onSecondaryFixedVariant = 324b4d
$tertiaryFixed = d7e3ff
$tertiaryFixedDim = b7c7ea
$onTertiaryFixed = 0a1b36
$onTertiaryFixedVariant = 374764
$term0 = 343434
$term1 = 769e00
$term2 = 49e2cf
$term3 = 75fcdd
$term4 = 76b5ba
$term5 = 7aaee9
$term6 = 80d8d3
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = 85b900
$term10 = 24f7e1
$term11 = cafff0
$term12 = a3c8c8
$term13 = a2c0f7
$term14 = 88ece5
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 67cdf1
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d1faee
$green = 8af1eb
$teal = 9eedf0
$sky = 93e9f2
$sapphire = 72d6e5
$blue = 5ccbe4
$lavender = 89d8ef
$klink = 0095a7
$klinkSelection = 0095a8
$kvisited = 008bb0
$kvisitedSelection = 008bb0
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bdb8
$kpositiveSelection = 00bdb9
$text = dde4e4
$subtext1 = bec8c9
$subtext0 = 899393
$overlay2 = 778080
$overlay1 = 646d6d
$overlay0 = 535b5b
$surface2 = 424a4a
$surface1 = 323939
$surface0 = 202627
$base = 0e1415
$mantle = 0e1415
$crust = 0d1314
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
