$primary_paletteKeyColor = 6fb8e3
$secondary_paletteKeyColor = 8bc9eb
$tertiary_paletteKeyColor = b4e4f6
$neutral_paletteKeyColor = 4d86b0
$neutral_variant_paletteKeyColor = 5e95bc
$background = 1b2d40
$onBackground = d6e2ee
$surface = 1b2d40
$surfaceDim = 152535
$surfaceBright = 304860
$surfaceContainerLowest = 10202f
$surfaceContainerLow = 182a3c
$surfaceContainer = 1e3347
$surfaceContainerHigh = 243a50
$surfaceContainerHighest = 304860
$onSurface = d6e2ee
$surfaceVariant = 304860
$onSurfaceVariant = 8bc9eb
$inverseSurface = d6e2ee
$inverseOnSurface = 1b2d40
$outline = 4d86b0
$outlineVariant = 304860
$shadow = 000000
$scrim = 000000
$surfaceTint = 6fb8e3
$primary = 6fb8e3
$onPrimary = 1b2d40
$primaryContainer = 4d86b0
$onPrimaryContainer = d6e2ee
$inversePrimary = 304860
$secondary = 8bc9eb
$onSecondary = 1b2d40
$secondaryContainer = 5e95bc
$onSecondaryContainer = d6e2ee
$tertiary = b4e4f6
$onTertiary = 1b2d40
$tertiaryContainer = 6fa4c9
$onTertiaryContainer = f2fcff
$error = ff7b7b
$onError = 601410
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = b4e4f6
$primaryFixedDim = 6fb8e3
$onPrimaryFixed = 1b2d40
$onPrimaryFixedVariant = 4d86b0
$secondaryFixed = d1eef8
$secondaryFixedDim = 8bc9eb
$onSecondaryFixed = 1b2d40
$onSecondaryFixedVariant = 5e95bc
$tertiaryFixed = f2fcff
$tertiaryFixedDim = b4e4f6
$onTertiaryFixed = 1b2d40
$onTertiaryFixedVariant = 6fa4c9
$term0 = 1b2d40
$term1 = 4d86b0
$term2 = 5e95bc
$term3 = 6fa4c9
$term4 = 6fb8e3
$term5 = 8bc9eb
$term6 = b4e4f6
$term7 = d6e2ee
$term8 = 304860
$term9 = 73a6cb
$term10 = 86b7d8
$term11 = 9dcae5
$term12 = f2fcff
$term13 = b1d8ee
$term14 = d1eef8
$term15 = ffffff
$rosewater = d1eef8
$flamingo = b4e4f6
$pink = 9dcae5
$mauve = 8bc9eb
$red = 73a6cb
$maroon = 6fa4c9
$peach = 86b7d8
$yellow = b1d8ee
$green = 5e95bc
$teal = 6fb8e3
$sky = 8bc9eb
$sapphire = 6fb8e3
$blue = 4d86b0
$lavender = b4e4f6
$klink = 6fb8e3
$klinkSelection = 6fb8e3
$kvisited = 4d86b0
$kvisitedSelection = 4d86b0
$knegative = ff7b7b
$knegativeSelection = ff7b7b
$kneutral = 8bc9eb
$kneutralSelection = 8bc9eb
$kpositive = 5e95bc
$kpositiveSelection = 5e95bc
$text = d6e2ee
$subtext1 = 8bc9eb
$subtext0 = 4d86b0
$overlay2 = 5e95bc
$overlay1 = 4d86b0
$overlay0 = 304860
$surface2 = 304860
$surface1 = 243a50
$surface0 = 1e3347
$base = 1b2d40
$mantle = 152535
$crust = 10202f
$success = 5e95bc
$onSuccess = 1b2d40
$successContainer = 4d86b0
$onSuccessContainer = d6e2ee
