cursor #dee4e4
cursor_text_color #bec8c9

foreground            #dee4e4
background            #0e1415
selection_foreground  #1c3437
selection_background  #b1cbcf
url_color             #81d3dd

color0   #0e1415
color1   #fe72a2
color2   #6edd78
color3   #fff572
color4   #69c6d1
color5   #185d66
color6   #81d3dd
color7   #dae6e8
color8   #848e8f
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #9de9f3
color13  #b4f6ff
color14  #cff9ff
color15  #f8feff
