cursor #dde4e4
cursor_text_color #bec8c9

foreground            #dde4e4
background            #0e1415
selection_foreground  #1b3436
selection_background  #b1cccd
url_color             #80d4d9

color0   #0e1415
color1   #f970a0
color2   #6cd976
color3   #fff472
color4   #68c8ce
color5   #186064
color6   #80d4d9
color7   #d6e3e3
color8   #828c8d
color9   #ff9fc1
color10  #a5ffad
color11  #fff8a5
color12  #9beaee
color13  #b5faff
color14  #cffcff
color15  #f8feff
