[colors.primary]
background = '#0e1415'
foreground = '#dde4e4'

[colors.selection]
text = '#dde4e4'
background = '#004f53'

[colors.cursor]
text = '#0e1415'
cursor = '#80d4d9'

[colors.normal]
black   = '#0e1415'
red     = '#f970a0'
green   = '#6cd976'
yellow  = '#fff472'
blue    = '#68c8ce'
magenta = '#186064'
cyan    = '#80d4d9'
white   = '#d6e3e3'

[colors.bright]
black   = '#828c8d'
red     = '#ff9fc1'
green   = '#a5ffad'
yellow  = '#fff8a5'
blue    = '#9beaee'
magenta = '#b5faff'
cyan    = '#cffcff'
white   = '#f8feff'
