[colors.primary]
background = '#131318'
foreground = '#e5e1e9'

[colors.selection]
text = '#e5e1e9'
background = '#454077'

[colors.cursor]
text = '#131318'
cursor = '#c6bfff'

[colors.normal]
black   = '#131318'
red     = '#ff7292'
green   = '#7fff98'
yellow  = '#ffd972'
blue    = '#b1a9f2'
magenta = '#453f76'
cyan    = '#c6bfff'
white   = '#f1efff'

[colors.bright]
black   = '#9a99a5'
red     = '#ff9fb5'
green   = '#a5ffb6'
yellow  = '#ffe6a5'
blue    = '#cec8ff'
magenta = '#d7d2ff'
cyan    = '#e5e2ff'
white   = '#f9f8ff'
