[colors.primary]
background = '#121318'
foreground = '#e3e2e9'

[colors.selection]
text = '#e3e2e9'
background = '#304578'

[colors.cursor]
text = '#121318'
cursor = '#b2c5ff'

[colors.normal]
black   = '#121318'
red     = '#ff7298'
green   = '#7fff93'
yellow  = '#fff872'
blue    = '#9ab0f2'
magenta = '#344476'
cyan    = '#b2c5ff'
white   = '#eff3ff'

[colors.bright]
black   = '#999ca5'
red     = '#ff9fb9'
green   = '#a5ffb3'
yellow  = '#fffba5'
blue    = '#bdcdff'
magenta = '#c9d6ff'
cyan    = '#dce4ff'
white   = '#f8faff'
